type: http
name: Validate field values
url: '{{baseUrl}}/orders/:orderId/fields/validate'
method: POST
headers:
  - key: Content-Type
    value: application/json
pathVariables:
  - key: orderId
    value: string
body:
  type: json
  content: '{}'
